# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 90acbb00b2af3f8273e0e423e9c7c89ff4555da85f2da157178bcf1981ac2294231c6a4d75f886af2f5e9c7d94370850c55791bedd431c42de735f2fed67d191

test:
  secret_key_base: 671b1ce8509fb7dc3b1f1fe5dca829a179c4bfcca2d1cddc9183d371036812f13055cd695d337a5f030296cc81268de781bdc91e2b2671ca06b9d8c78706ea1d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
